import "../../styles/globals.css";
import Header from "./header";
import Footer from "./footer";
import Head from "./head";
import Provider from "./Provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head />
      <body className="flex flex-col">
        <Provider>
          <Header />
          <main className="grow h-screen">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
